(() => {
  const $=id=>document.getElementById(id);
  let token=sessionStorage.getItem('belarcPortalToken'), me, tab='new', known=new Set(), timer, deferredInstall, departments=[];
  const fragment=new URLSearchParams(location.hash.slice(1)).get('access_token'); if(fragment){token=fragment;sessionStorage.setItem('belarcPortalToken',token);history.replaceState(null,'',location.pathname+location.search);}
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const status=m=>{$('refresh-status').textContent=m;}; const receiver=()=>Boolean(me?.receive_departments?.length);
  const statusLabel=s=>({open:'Aberto',in_progress:'Em atendimento',waiting:'Aguardando',done:'Concluído'}[s]||s);
  async function api(path,method='GET',body){const r=await fetch(path,{method,headers:{...(token?{Authorization:`Bearer ${token}`}:{}) ,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok){let m='';try{m=(await r.json()).error||'';}catch(_){}throw Error(m||`Erro ${r.status}`);}return r.status===204?null:r.json();}
  const departmentName=slug=>departments.find(d=>d.slug===slug)?.name||slug;
  async function loadDepartments(){departments=await api('/api/ticket-departments');const select=$('department');const prior=select.value;select.innerHTML=departments.map(d=>`<option value="${esc(d.slug)}">${esc(d.name)}</option>`).join('');if(departments.some(d=>d.slug===prior))select.value=prior;if(!departments.length){select.innerHTML='<option>Sem setores disponíveis</option>';select.disabled=true;$('ticket-form').querySelector('button').disabled=true;}}
  function card(t,manage){const comments=(t.comments||[]).length?(t.comments||[]).map(c=>`<div class="comment"><strong>${esc(c.author_name||'Sistema')}</strong><br>${esc(c.body)}<br><span class="meta">${new Date(c.created_at).toLocaleString('pt-BR')}</span></div>`).join(''):'<p class="hint">Sem mensagens adicionais.</p>';const controls=manage&&t.status!=='done'?`<div class="ticket-actions"><label class="meta">Andamento<select data-status="${esc(t.id)}"><option value="open" ${t.status==='open'?'selected':''}>Aberto</option><option value="in_progress" ${t.status==='in_progress'?'selected':''}>Em atendimento</option><option value="waiting" ${t.status==='waiting'?'selected':''}>Aguardando</option></select></label><button data-save="${esc(t.id)}">Salvar andamento</button><button data-close="${esc(t.id)}">Concluir</button></div>`:'';return `<article class="ticket"><div class="section-kicker">${esc(t.code)} · ${esc(departmentName(t.department))}</div><h3>${esc(t.title)}</h3><span class="badge">${esc(statusLabel(t.status))}</span><span class="badge">${esc(t.priority||'normal')}</span><p class="meta">${esc(t.hostname_snapshot||'PC não informado')} · atualizado ${new Date(t.updated_at).toLocaleString('pt-BR')}</p>${t.owner_name_snapshot?`<p class="meta">Solicitante: ${esc(t.owner_name_snapshot)}</p>`:''}${t.description?`<p>${esc(t.description)}</p>`:''}<div class="comments"><strong>Conversa</strong>${comments}${t.status!=='done'?`<form class="comment-form" data-comment="${esc(t.id)}"><input maxlength="1000" required placeholder="Escreva uma atualização…"><button type="submit">Enviar</button></form>`:''}</div>${controls}</article>`;}
  async function render(){if(tab==='new'){$('new-ticket').classList.remove('hidden');$('ticket-list').classList.add('hidden');return;}$('new-ticket').classList.add('hidden');$('ticket-list').classList.remove('hidden');const received=tab==='received', list=await api(received?'/api/tickets':'/api/tickets/mine');$('queue-title').textContent=received?'Chamados recebidos':'Meus chamados';$('queue-note').textContent=received?`Este computador recebe chamados de: ${me.receive_departments.map(departmentName).join(', ')}.`:'Chamados abertos a partir deste computador.';$('tickets').innerHTML=list.length?list.map(t=>card(t,received)).join(''):'<p class="hint">Nenhum chamado encontrado.</p>';bind();status(`Atualizado às ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`);}
  async function poll(){if(!receiver())return;const list=await api('/api/tickets'), ids=new Set(list.map(t=>t.id)), fresh=[...ids].filter(id=>!known.has(id)), baseline=known.size>0;known=ids;if(baseline&&fresh.length){const m=fresh.length===1?'Há um novo chamado recebido.':`Há ${fresh.length} novos chamados recebidos.`;status(m);if(window.isSecureContext&&Notification.permission==='granted')new Notification('Portal de Chamados',{body:m});}if(tab==='received')await render();}
  function bind(){document.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{try{await api(`/api/tickets/${b.dataset.save}`,'PATCH',{status:document.querySelector(`[data-status="${b.dataset.save}"]`).value});await render();}catch(e){alert(e.message);}});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=async()=>{const resolution=prompt('Descreva brevemente a solução aplicada:','Concluído pelo setor responsável.');if(resolution===null)return;try{await api(`/api/tickets/${b.dataset.close}/close`,'POST',{resolution});await render();}catch(e){alert(e.message);}});document.querySelectorAll('[data-comment]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const i=f.querySelector('input');try{await api(`/api/tickets/${f.dataset.comment}/comments`, 'POST',{body:i.value});await render();}catch(e){alert(e.message);}});}
  async function machines(){const list=await api('/api/portal/machines');$('machine').innerHTML=list.map(m=>`<option value="${esc(m.id)}">${esc(m.hostname)}</option>`).join('');if(list[0])$('subtitle').textContent=`Este computador: ${list[0].hostname}`;if(!list.length){$('ticket-form').querySelector('button').disabled=true;$('ticket-error').textContent='Sua conta ainda não está vinculada a um computador. Peça apoio à TI.';}}
  function file(f){if(f.size>8*1024*1024)return Promise.reject(Error(`O anexo ${f.name} excede o limite de 8 MB.`));return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok({filename:f.name,content_base64:String(r.result).split(',')[1]||''});r.onerror=()=>no(Error(`Não foi possível ler ${f.name}.`));r.readAsDataURL(f);});}
  async function choose(next){if(next==='new'&&!me.can_open_ticket||next==='received'&&!receiver())return;tab=next;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));await render();}
  async function start(){clearInterval(timer);try{me=await api('/api/portal/auth/me');if(!me.authenticated)throw Error();await loadDepartments();$('launch-card').classList.add('hidden');$('portal').classList.remove('hidden');$('logout').classList.remove('hidden');$('refresh').classList.remove('hidden');$('connection-state').classList.remove('offline');$('connection-state').lastChild.textContent='Conectado';document.querySelector('[data-tab="new"]').classList.toggle('hidden',!me.can_open_ticket);document.querySelector('[data-tab="received"]').classList.toggle('hidden',!receiver());if(me.can_open_ticket)await machines();await poll();await choose(me.can_open_ticket?'new':'received');timer=setInterval(()=>poll().catch(()=>status('Não foi possível atualizar agora.')),30000);}catch(_){sessionStorage.removeItem('belarcPortalToken');token=null;me=null;known=new Set();$('launch-card').classList.remove('hidden');$('portal').classList.add('hidden');$('logout').classList.add('hidden');$('refresh').classList.add('hidden');$('connection-state').classList.add('offline');$('connection-state').lastChild.textContent='Sem conexão';}}
  $('ticket-form').onsubmit=async e=>{e.preventDefault();$('ticket-error').textContent='';try{const attachments=await Promise.all([...$('attachments').files].map(file));await api('/api/tickets','POST',{machine_id:$('machine').value,department:$('department').value,priority:$('priority').value,title:$('title').value,description:$('description').value,attachments});e.currentTarget.reset();await machines();await choose('mine');}catch(err){$('ticket-error').textContent=err.message;}};
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>choose(b.dataset.tab).catch(e=>status(e.message)));$('refresh').onclick=()=>poll().then(render).catch(e=>status(e.message));$('logout').onclick=async()=>{try{await api('/api/portal/auth/logout','POST');}catch(_){}sessionStorage.removeItem('belarcPortalToken');token=null;await start();};$('enable-notifications').onclick=async()=>{if(window.isSecureContext&&'Notification'in window){await Notification.requestPermission();$('enable-notifications').classList.add('hidden');}};
  if('serviceWorker'in navigator&&(window.isSecureContext||location.hostname==='localhost'))navigator.serviceWorker.register('/cliente-sw.js?v=portal-autenticado-v2').catch(()=>{});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('install-app').classList.remove('hidden');});$('install-app').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('install-app').classList.add('hidden');};if(window.isSecureContext&&'Notification'in window&&Notification.permission==='default')$('enable-notifications').classList.remove('hidden');start();
})();
